/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    media: Media;
    services: Service;
    'contact-submissions': ContactSubmission;
    test: Test;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    test: TestSelect<false> | TestSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Page title (used in browser tab and admin)
   */
  title: string;
  /**
   * URL path for this page (e.g., "home", "about", "menu")
   */
  slug: string;
  layout: (
    | {
        /**
         * Script logo for 'Keno\'s' text (uses default if not provided)
         */
        logo?: (string | null) | Media;
        /**
         * Text after the logo (e.g., 'Today', 'Legacy', 'Story')
         */
        headingSuffix?: string | null;
        /**
         * Description text below the heading
         */
        content?: string | null;
        primaryButton?: {
          text?: string | null;
          link?: string | null;
        };
        secondaryButton?: {
          text?: string | null;
          link?: string | null;
        };
        /**
         * Background image for the hero area
         */
        backgroundImage?: (string | null) | Media;
        /**
         * Images for the horizontal scrolling ticker
         */
        gallery?:
          | {
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'kenosToday';
      }
    | {
        /**
         * First part of heading (before logo)
         */
        heading?: string | null;
        /**
         * Logo to display in heading (Keno's script logo)
         */
        headingLogo?: (string | null) | Media;
        /**
         * Text after the logo
         */
        subheading?: string | null;
        /**
         * Introductory paragraph below the heading
         */
        content?: string | null;
        /**
         * Background image for the hero section
         */
        backgroundImage?: (string | null) | Media;
        /**
         * Team photo that overlays on the right side with red border
         */
        overlayImage?: (string | null) | Media;
        primaryButton?: {
          text?: string | null;
          link?: string | null;
        };
        secondaryButton?: {
          text?: string | null;
          link?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'staffHero';
      }
    | {
        /**
         * Italic introduction text (use double line breaks for paragraphs)
         */
        introText?: string | null;
        /**
         * Team members to display in the grid
         */
        staffMembers?:
          | {
              /**
               * Display name (e.g., "Meet Shauna")
               */
              name: string;
              /**
               * Job title (e.g., "General Manager")
               */
              title?: string | null;
              /**
               * Staff member photo (portrait orientation works best)
               */
              image?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'staffGrid';
      }
    | {
        /**
         * Section heading (displayed in Marble Dreams font)
         */
        heading: string;
        /**
         * Main text content (use double line breaks for paragraphs)
         */
        content: string;
        /**
         * Image displayed on the right side
         */
        image?: (string | null) | Media;
        button?: {
          text?: string | null;
          link?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'familySection';
      }
    | {
        /**
         * Choose how to display the photos
         */
        displayMode?: ('notecard' | 'ticker') | null;
        /**
         * Show the EST. year section (uncheck to hide)
         */
        showYear?: boolean | null;
        /**
         * Small label above the year (e.g., "EST.", "SINCE") - only shown if "Show Year" is checked
         */
        yearLabel?: string | null;
        /**
         * Year to display prominently - only shown if "Show Year" is checked
         */
        year?: string | null;
        /**
         * Historical photos to display
         */
        images?:
          | {
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'historyTimelineTicker';
      }
    | {
        /**
         * Small uppercase subtitle (e.g., "TASTE THE CLASSICS")
         */
        subtitle?: string | null;
        /**
         * Body text content
         */
        content?: string | null;
        /**
         * Two images that stack/overlap on the right side
         */
        images?:
          | {
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'classicsSection';
      }
    | {
        /**
         * Main headline (e.g., "Our History")
         */
        heading: string;
        /**
         * History description text
         */
        content?: string | null;
        /**
         * Background image (e.g., restaurant exterior)
         */
        backgroundImage?: (string | null) | Media;
        /**
         * Historical photo that hangs below the hero section
         */
        overlayImage?: (string | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'historyHero';
      }
    | {
        /**
         * Main headline (e.g., "You're Only A Stranger Once")
         */
        heading: string;
        /**
         * Restaurant address to display on hero
         */
        address?: string | null;
        /**
         * Google Maps link for the address
         */
        addressLink?: string | null;
        /**
         * Large food photography background
         */
        backgroundImage?: (string | null) | Media;
        primaryButton?: {
          text?: string | null;
          link?: string | null;
        };
        secondaryButton?: {
          text?: string | null;
          link?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'kenosHero';
      }
    | {
        awards?:
          | {
              /**
               * Award title (e.g., "Best Breakfast in Orange County")
               */
              title: string;
              /**
               * Select the award source logo to display
               */
              source?: ('hotlist' | 'register') | null;
              /**
               * Circular badge design with stars
               */
              badgeImage?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Logo displayed between badges
         */
        centerLogo?: (string | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'awardsSection';
      }
    | {
        /**
         * Main heading (e.g., "Thanksgiving Day Menus")
         */
        heading: string;
        /**
         * Subheading below main heading (e.g., "Pre-Order Family Meals or Dine-In")
         */
        subheading?: string | null;
        /**
         * Promotion images (menu flyers, product photos) - displayed on right side with overflow and rounded corners
         */
        promotionImages?:
          | {
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Show the date/info box above the CTA button
         */
        showDateBox?: boolean | null;
        /**
         * First line in date box (e.g., "Thursday November 27th, 2025") - only shown if "Show Date Box" is checked
         */
        dateBoxLine1?: string | null;
        /**
         * Second line in date box (e.g., "Open from 7:00 am - 6:00 pm") - only shown if "Show Date Box" is checked
         */
        dateBoxLine2?: string | null;
        /**
         * Third line in date box (e.g., "Holiday Menu 11am - Sold Out") - only shown if "Show Date Box" is checked
         */
        dateBoxLine3?: string | null;
        button?: {
          text?: string | null;
          link?: string | null;
        };
        /**
         * Background image for the section
         */
        backgroundImage?: (string | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'promotionSection';
      }
    | {
        heading: string;
        description?: string | null;
        button?: {
          text?: string | null;
          link?: string | null;
        };
        gallery?:
          | {
              image: string | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'orderOnlineSection';
      }
    | {
        heading: string;
        content: string;
        button?: {
          text?: string | null;
          link?: string | null;
        };
        /**
         * Food photography with dark overlay
         */
        backgroundImage?: (string | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'destinationSection';
      }
    | {
        /**
         * Circular profile photo
         */
        photo?: (string | null) | Media;
        /**
         * Label above name (e.g., "OWNER", "CHEF")
         */
        label?: string | null;
        name: string;
        /**
         * Biography text (use double line breaks for paragraphs)
         */
        bio?: string | null;
        /**
         * Label for favorite meal section
         */
        favoriteMealLabel?: string | null;
        /**
         * Favorite meal quote
         */
        favoriteMeal?: string | null;
        button?: {
          text?: string | null;
          link?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'ownerProfileSection';
      }
    | {
        /**
         * Main headline text
         */
        heading: string;
        /**
         * Supporting text below the headline
         */
        subheading?: string | null;
        /**
         * Hero background image
         */
        backgroundImage?: (string | null) | Media;
        primaryButton?: {
          text?: string | null;
          link?: string | null;
        };
        secondaryButton?: {
          text?: string | null;
          link?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        title: string;
        subtitle?: string | null;
        content: {
          [k: string]: unknown;
        }[];
        image?: (string | null) | Media;
        imagePosition?: ('left' | 'right') | null;
        features?:
          | {
              /**
               * Icon name or emoji
               */
              icon?: string | null;
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'about';
      }
    | {
        title: string;
        subtitle?: string | null;
        items?:
          | {
              name: string;
              description?: string | null;
              price?: string | null;
              image?: (string | null) | Media;
              /**
               * e.g., Appetizer, Main Course, Dessert
               */
              category?: string | null;
              featured?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menuHighlights';
      }
    | {
        title?: string | null;
        subtitle?: string | null;
        images?:
          | {
              image: string | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        layout?: ('grid' | 'masonry' | 'carousel') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        title?: string | null;
        subtitle?: string | null;
        testimonials?:
          | {
              quote: string;
              author: string;
              /**
               * e.g., Food Critic, Regular Customer
               */
              role?: string | null;
              avatar?: (string | null) | Media;
              /**
               * Star rating (1-5)
               */
              rating?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        title?: string | null;
        subtitle?: string | null;
        address?: string | null;
        phone?: string | null;
        email?: string | null;
        hours?:
          | {
              day: string;
              hours: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Google Maps embed code or map URL
         */
        mapEmbed?: string | null;
        showContactForm?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact';
      }
    | {
        title?: string | null;
        content: {
          [k: string]: unknown;
        }[];
        backgroundColor?: ('white' | 'light-gray' | 'dark' | 'primary') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        heading: string;
        description?: string | null;
        button: {
          text: string;
          link: string;
        };
        backgroundImage?: (string | null) | Media;
        style?: ('centered' | 'left' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
  )[];
  meta?: {
    /**
     * Override the page title for SEO (defaults to page title)
     */
    title?: string | null;
    /**
     * Meta description for search engines
     */
    description?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    /**
     * Open Graph image for social sharing
     */
    image?: (string | null) | Media;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage images and media files for the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for accessibility and SEO
   */
  alt: string;
  /**
   * Optional caption to display with the image
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  /**
   * Icon name from iconoir-react (e.g., "headset-help", "chart-line")
   */
  icon?: string | null;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  /**
   * Short tagline or subtitle for the service
   */
  tagline?: string | null;
  /**
   * Longer description paragraph for the service
   */
  detailedDescription?: string | null;
  serviceItems?:
    | {
        /**
         * Icon name from iconoir-react
         */
        icon?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Order in which the service appears (lower numbers first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message: string;
  status?: ('new' | 'contacted' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test".
 */
export interface Test {
  id: string;
  title: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'test';
        value: string | Test;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        kenosToday?:
          | T
          | {
              logo?: T;
              headingSuffix?: T;
              content?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              backgroundImage?: T;
              gallery?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        staffHero?:
          | T
          | {
              heading?: T;
              headingLogo?: T;
              subheading?: T;
              content?: T;
              backgroundImage?: T;
              overlayImage?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              id?: T;
              blockName?: T;
            };
        staffGrid?:
          | T
          | {
              introText?: T;
              staffMembers?:
                | T
                | {
                    name?: T;
                    title?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        familySection?:
          | T
          | {
              heading?: T;
              content?: T;
              image?: T;
              button?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              id?: T;
              blockName?: T;
            };
        historyTimelineTicker?:
          | T
          | {
              displayMode?: T;
              showYear?: T;
              yearLabel?: T;
              year?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        classicsSection?:
          | T
          | {
              subtitle?: T;
              content?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        historyHero?:
          | T
          | {
              heading?: T;
              content?: T;
              backgroundImage?: T;
              overlayImage?: T;
              id?: T;
              blockName?: T;
            };
        kenosHero?:
          | T
          | {
              heading?: T;
              address?: T;
              addressLink?: T;
              backgroundImage?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              id?: T;
              blockName?: T;
            };
        awardsSection?:
          | T
          | {
              awards?:
                | T
                | {
                    title?: T;
                    source?: T;
                    badgeImage?: T;
                    id?: T;
                  };
              centerLogo?: T;
              id?: T;
              blockName?: T;
            };
        promotionSection?:
          | T
          | {
              heading?: T;
              subheading?: T;
              promotionImages?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              showDateBox?: T;
              dateBoxLine1?: T;
              dateBoxLine2?: T;
              dateBoxLine3?: T;
              button?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        orderOnlineSection?:
          | T
          | {
              heading?: T;
              description?: T;
              button?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              gallery?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        destinationSection?:
          | T
          | {
              heading?: T;
              content?: T;
              button?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        ownerProfileSection?:
          | T
          | {
              photo?: T;
              label?: T;
              name?: T;
              bio?: T;
              favoriteMealLabel?: T;
              favoriteMeal?: T;
              button?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              subtitle?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        menuHighlights?:
          | T
          | {
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    name?: T;
                    description?: T;
                    price?: T;
                    image?: T;
                    category?: T;
                    featured?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              subtitle?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              subtitle?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              subtitle?: T;
              address?: T;
              phone?: T;
              email?: T;
              hours?:
                | T
                | {
                    day?: T;
                    hours?: T;
                    id?: T;
                  };
              mapEmbed?: T;
              showContactForm?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              title?: T;
              content?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              button?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              backgroundImage?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  description?: T;
  tagline?: T;
  detailedDescription?: T;
  serviceItems?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test_select".
 */
export interface TestSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  mainNav: {
    label: string;
    href: string;
    openInNewTab?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Navigation links for the left column of the footer
   */
  footerLeftColumn?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Navigation links for the right column of the footer
   */
  footerRightColumn?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Restaurant hours displayed in the footer
   */
  footerHours?: {
    title?: string | null;
    line1?: string | null;
    line2?: string | null;
  };
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    yelp?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerLeftColumn?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerRightColumn?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerHours?:
    | T
    | {
        title?: T;
        line1?: T;
        line2?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        yelp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}